FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY javascript-pixi/package*.json ./

# Install app dependencies
RUN npm install

# Copy app source
COPY javascript-pixi/ .

# Build the app
RUN npm run build

# Install http-server to serve the static files
RUN npm install -g http-server

# Expose port 8080
EXPOSE 8080

# Define command to run the app
CMD [ "http-server", "dist", "-p", "8080" ]