FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY javascript-pixi/package.json .
RUN npm install

# Bundle app source
COPY javascript-pixi/src src

# Build the app
RUN npm run build

# Install http-server to serve the static files
RUN npm install -g http-server

# Expose the port the app runs on
EXPOSE 8080

# Define the command to run the app
CMD [ "http-server", "dist" ]